alias sourcefoxy='source ${ROS2_INSTALL_PATH}/setup.bash'
alias sourcenoetic='source ${ROS1_INSTALL_PATH}/setup.bash'
alias sourcebridge='source /workspaces/ros1_bridge_ws/install/setup.bash'

function load_ros1_bridge_params() {
    echo "[PARAM BRIDGE LAUNCHER] Launching load_params.launch"
    cd /workspaces/ros1_jackal_msgs_ws
    source devel/setup.bash
    roslaunch param_bridge_launcher load_params.launch
}

function run_ros1_param_bridge() {
    echo "[BRIDGE] Starting parameter bridge"
    source /opt/ros/noetic/setup.bash
    source /opt/ros/foxy/setup.bash
    source /workspaces/ros1_bridge_ws/install/setup.bash
    ros2 run ros1_bridge parameter_bridge
}